version: 2.1
orbs:
  happo: happo/happo@2.0.0
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: npminstall
          command: npm install
      - run:
          name: happo
          command: VERBOSE=true npm run happo-ci-circleci